FROM node:20.12.0-alpine3.19

WORKDIR /usr/src/app

# Copy the necessary files
COPY package.json package-lock.json turbo.json tsconfig.json ./

COPY apps ./apps
COPY packages ./packages

# Install dependencies
RUN npm install

# Run Prisma generate, migrate, and seed
RUN npm run db:generate

# Build the application
RUN npm run build

CMD ["npm", "run", "start-user-app"]
